---
- hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - command: /usr/local/bin/lein --version
      register: leinengen_test_output
    - name: len --version
      debug:
        msg: '{{ leinengen_test_output.stdout }}'
