---
- hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - command: bash -l -c '/usr/local/bin/lein --version'
      register: leinengen_test_output
    - name: lein --version
      debug:
        msg: '{{ leinengen_test_output.stdout }}'
