---
- include_role:
    name: andrewrothstein.temurin
  vars:
    openjdk_app: jdk
- include_role:
    name: andrewrothstein.bash
- include_role:
    name: andrewrothstein.openssl
- include_role:
    name: andrewrothstein.wget
- name: downloading {{ leinengen_url }}
  become: true
  become_user: root
  get_url:
    url: '{{ leinengen_url }}'
    dest: '{{ leinengen_exe }}'
    mode: 0755
- name: initializing with {{ leinengen_exe }}
  become: true
  become_user: root
  command: bash -lc {{ leinengen_install_dir }}/lein
  args:
    creates: '{{ lookup("env","HOME") }}/.lein'
