---
- name: downloading {{ leinengen_url }}
  become: yes
  become_user: root
  get_url:
    url: '{{ leinengen_url }}'
    dest: '{{ leinengen_exe }}'
    mode: 0755
- name: initializing with {{ leinengen_exe }}
  become: yes
  become_user: root
  command: bash -l -c {{ leinengen_install_dir }}/lein
  args:
    creates: '{{ lookup("env","HOME") }}/.lein'
